# Generated by Django 3.1.2 on 2024-11-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bus_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
