# Generated by Django 3.1.2 on 2024-10-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.ManyToManyField(related_name='tickets', to='flight.Seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='num_passenger',
            field=models.IntegerField(null=True),
        ),
    ]
