# Generated by Django 3.1.2 on 2024-11-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20241102_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='flight.bus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='coupon_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='flight.coupon'),
        ),
    ]
