# Generated by Django 3.1.2 on 2024-10-31 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20241101_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='bus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.bus'),
        ),
    ]
