# Generated by Django 3.1.2 on 2024-10-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20241101_0357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
    ]
