# Generated by Django 3.1.2 on 2024-11-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_auto_20241101_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ref_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
